"""add_provider_settings

Revision ID: 9e0a8735e74e
Revises: 3a671db91ad8
Create Date: 2026-05-18 15:39:00.773198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e0a8735e74e'
down_revision: Union[str, Sequence[str], None] = '3a671db91ad8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_settings_id'), 'provider_settings', ['id'], unique=False)
    op.create_index(op.f('ix_provider_settings_priority'), 'provider_settings', ['priority'], unique=False)
    op.create_index(op.f('ix_provider_settings_provider_name'), 'provider_settings', ['provider_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provider_settings_provider_name'), table_name='provider_settings')
    op.drop_index(op.f('ix_provider_settings_priority'), table_name='provider_settings')
    op.drop_index(op.f('ix_provider_settings_id'), table_name='provider_settings')
    op.drop_table('provider_settings')
    # ### end Alembic commands ###
